source: .
destination: ./_site
layouts_dir: ./_layouts
includes_dir: ./_includes
name: Lurida the Isolated Network Cart
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
baseurl: ""
show_dir_listing: false